apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp
        image: myapp:blue
        ports:
        - containerPort: 5000

