apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: default

data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'myapp'
        static_configs:
          - targets: ['myapp-service:80']
